# Generated by Django 2.0.7 on 2018-08-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180815_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
